#!/bin/bash

sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y install emacs python python-numpy python-scipy \
  python-matplotlib python-imaging python-nltk python-networkx r-base \
  r-base-dev git xli